[package]
name = "create_fruit_app"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/orhun/packaging-rust-for-npm"
authors = ["Igor Ilic"]

[dependencies]
chrono = "0.4.33"
clap = { version = "4.4.18", features = ["derive"] }
inquire = { version = "0.6.2", features = ["date"] }
